#ifndef CONFIG_HPP
#define CONFIG_HPP

//#define DEBUG_MODE_GLOBAL

#define DEBUG_MODE_PROCESS_CONTROL
#define DEBUG_MODE_I2C
//#define DEBUG_MODE_CAMERA
//#define DEBUG_MODE_PROJECTOR
//#define DEBUG_MODE_DYNAMIC_IMAGE
#define DEBUG_MODE_RECIPE
//#define DEBUG_MODE_PROCESS_CONTROL

#ifdef DEBUG_MODE_GLOBAL
#define DEBUG_MODE_PROCESS_CONTROL
#define DEBUG_MODE_I2C
#define DEBUG_MODE_CAMERA
#define DEBUG_MODE_PROJECTOR
#define DEBUG_MODE_DYNAMIC_IMAGE
#define DEBUG_MODE_RECIPE
#define DEBUG_MODE_PROCESS_CONTROL
#endif

#endif // CONFIG_HPP
