#ifndef CONFIG_HPP
#define CONFIG_HPP

//#define DEBUG_MODE_GLOBAL

#ifdef DEBUG_MODE_GLOBAL
#define DEBUG_MODE_I2C
#define DEBUG_MODE_CAMERA
#define DEBUG_MODE_PROJECTOR
#define DEBUG_MODE_DYNAMIC_IMAGE
#endif

//#define DEBUG_MODE_I2C
#define DEBUG_MODE_CAMERA
//#define DEBUG_MODE_PROJECTOR
//#define DEBUG_MODE_DYNAMIC_IMAGE

#endif // CONFIG_HPP
